eureka:
    client:
        serviceUrl:
            defaultZone: http://localhost:9600/eureka/
logging:
    level:
        root: debug
security:
    oauth2:
        client:
            client-id: sample1234
            client-secret: samplepassword
        resource:
            jwt:
                key-value: samplejwt
spring:
    application:
        name: gateway
zuul:
    routes:
        first:
            path: /first/**
            url: http://localhost:9800
            strip-prefix: true
        second:
            path: /second/**
            strip-prefix: true
    sensitiveHeaders: 'Cookie,Set-Cookie'
